target 'EndpointOwnershipDemo' do
    use_frameworks!
    pod 'Fabric'
    pod 'TwitterKit'
    pod 'TwitterCore'
    pod 'Google/SignIn'
    pod 'FBSDKLoginKit', '~> 4.15'
    pod 'Kaa', :path => './libs/kaa-ep-sdk'

end

