/**
 *  Copyright 2014-2016 CyberVision, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

#import "ViewController.h"
#import "CredentialsDemoFailoverStrategy.h"

@import Kaa;

@interface ViewController () <KaaClientStateDelegate, ProfileContainer>

@property (weak, nonatomic) IBOutlet UIView *autogeneratedKeysView;
@property (weak, nonatomic) IBOutlet UITextView *logTextView;

@property (nonatomic, strong) id<KaaClient> kaaClient;
@property (nonatomic) BOOL isAutogeneratedKeys;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    [self addLogWithText:@"CredentialsDemo started"];
    
    self.logTextView.hidden = YES;
    self.logTextView.alpha = 1.0;
}

#pragma mark - KaaClientStateDelegate

- (void)onStarted {
    [self addLogWithText:@"Kaa client started"];
}

- (void)onStopped {
    [self addLogWithText:@"Kaa client stopped"];
}

- (void)onStartFailureWithException:(NSException *)exception {
    [self addLogWithText:[NSString stringWithFormat:@"START FAILURE: %@ : %@", exception.name, exception.reason]];
}

- (void)onPaused {
    [self addLogWithText:@"Client paused"];
}

- (void)onPauseFailureWithException:(NSException *)exception {
    [self addLogWithText:[NSString stringWithFormat:@"PAUSE FAILURE: %@ : %@", exception.name, exception.reason]];
}

- (void)onResume {
    [self addLogWithText:@"Client resumed"];
}

- (void)onResumeFailureWithException:(NSException *)exception {
    [self addLogWithText:[NSString stringWithFormat:@"RESUME FAILURE: %@ : %@", exception.name, exception.reason]];
    
}

- (void)onStopFailureWithException:(NSException *)exception {
    [self addLogWithText:[NSString stringWithFormat:@"STOP FAILURE: %@ : %@", exception.name, exception.reason]];
}


#pragma mark - PorfileContainer

- (KAAProfileEmptyData *)getProfile {
    return [[KAAProfileEmptyData alloc] init];
}

#pragma mark - Supporting methods

- (void)startKaaPerformance {
    self.autogeneratedKeysView.hidden = YES;
    self.logTextView.hidden = NO;
    
    //Create a Kaa client with the Kaa default context.
    if (self.isAutogeneratedKeys) {
        self.kaaClient = [KaaClientFactory clientWithContext:[[DefaultKaaPlatformContext alloc] init] stateDelegate:self];
        [self addLogWithText:[NSString stringWithFormat:@"Endpoint key hash: %@", [self.kaaClient getEndpointKeyHash]]];
        [self addLogWithText:[NSString stringWithFormat:@"Public key body: %@", [KeyUtils getPublicKey]]];
    } else {
        self.kaaClient = [KaaClientFactory clientWithContext:[[DefaultKaaPlatformContext alloc] init] stateDelegate:self autoGeneratedKeys:NO];
    }
    
    [self.kaaClient setFailoverStrategy:[[CredentialsDemoFailoverStrategy alloc] init]];
    
    [self.kaaClient setProfileContainer:self];
    
    // Start the Kaa client and connect it to the Kaa server.
    [self.kaaClient start];
}

- (void)addLogWithText:(NSString *) text {
    NSLog(@"%@", text);
    dispatch_async(dispatch_get_main_queue(), ^{
        self.logTextView.text = [NSString stringWithFormat:@"%@%@\n", self.logTextView.text, text];
    });
}

#pragma mark - Actions

- (IBAction)autogeneratedKeysTapped:(id)sender {
    self.isAutogeneratedKeys = YES;
    [self startKaaPerformance];
}

- (IBAction)defaultKeysStrategyTapped:(id)sender {
    self.isAutogeneratedKeys = NO;
    [self startKaaPerformance];
}

@end
