---
project_url:  http://www.kaaproject.org/
github_url_latest: http://github.com/kaaproject/sample-apps/tree/develop/
github_url: http://github.com/kaaproject/sample-apps/
copyright_text: "Copyright © 2014-2016, CyberVision, Inc."
copyright_url: http://www.cybervisiontech.com/
sidebar_img_path: /public/kaa-avatar.png
google_analytics_property_id: UA-47512871-7